[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
evm_version = "paris"
optimizer = true
optimizer_runs = 200
bytecode_hash = "ipfs"

remappings = [
  "forge-std/=lib/forge-std/src/",
]

fs_permissions = [
  { access = "read-write", path = "./deployments" }
]

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
int_types = "short"
quote_style = "double"
number_underscore = "preserve"
